# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 305c173c47f422a88f4685f7f0526f388a64401c7ced3288328f24bb439479248601f841059878fed2f91402eead1670567c7a52932b5607f35f48e7d8cd9f57

test:
  secret_key_base: a2f7a4ff453d25f732bc9c0d9cc0632213b26f2ce223beacdc06213a2ea7fe5c1e3604d0bd4c518b5d8900eca81aabe3e7fe533e6449932d9404fbdc95f03958

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
